// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOZ8Hw_rRVkI5c2i4Kn9UvrvnjCjAccqk',
    appId: '1:365863147603:web:3f2be4162c8c6c28b18ea6',
    messagingSenderId: '365863147603',
    projectId: 'fashion-style-5b51d',
    authDomain: 'fashion-style-5b51d.firebaseapp.com',
    storageBucket: 'fashion-style-5b51d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8-02EgxWdgFfYGGliQDvsRoCl4pukrIs',
    appId: '1:365863147603:android:3752bbeedd0e0c50b18ea6',
    messagingSenderId: '365863147603',
    projectId: 'fashion-style-5b51d',
    storageBucket: 'fashion-style-5b51d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_nTQiMbNrJJaqWTDhF5d7tfp-DkAiEM',
    appId: '1:365863147603:ios:3d94b004ed66b52bb18ea6',
    messagingSenderId: '365863147603',
    projectId: 'fashion-style-5b51d',
    storageBucket: 'fashion-style-5b51d.appspot.com',
    androidClientId: '365863147603-70q0n6o1jo27rus01udu2k2f64d6pkb9.apps.googleusercontent.com',
    iosClientId: '365863147603-tti2b0itq5no50tvns75ett3r0jrve1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionStyle',
  );
}
